name: Radar Scan

on:
  push:
    branches: [main]
    paths:
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    uses: ${{ github.repository_owner }}/tech-radar-ppm/.github/workflows/scan-dependencies.yml@main
    with:
      product-name: todo-app
    secrets:
      RADAR_DATA_PUSH_TOKEN: ${{ secrets.RADAR_DATA_PUSH_TOKEN }}
